### ISSUE TITLE
How to use web interface?

### ISSUE THREAD

**Issue by danielpmc** [Ankrad/Backup#2]
Hello, 
How do i use the web interface and is there a open source version of the one on glitch? (from the url that the bot gives https://discord-backup.glitch.me/ ) 

Thanks :)

**Comment by Ankrad** [comment]
Yes, I originally had that on glitch separate from the bot. I'll just combine the two and add it to the source.

**Comment by danielpmc** [comment]
Ok. downloaded the latest master but is there a redirect_url after you sign in with discord on the interface?

**Comment by Ankrad** [comment]
Yeah, you'll need to add in the redirect URL to the discord developer application under the Oauth tab to `/api/callback`

**Comment by danielpmc** [comment]
Ok that works but one problem is i keep getting 
Error: Cannot find module 'ejs'

I tried to install ejs multiple times. it installs but says the same thing (i can access the website but not click any guilds)

**Comment by Ankrad** [comment]
Did you do `npm install ejs` in the right directory and restart the bot?

**Comment by danielpmc** [comment]
yeah. still get the same error

**Comment by Ankrad** [comment]
Do you have any errors when installing ejs?

**Comment by danielpmc** [comment]
No errors installs fine but doesnt work.

**Comment by Ankrad** [comment]
What doesn't work?

**Comment by danielpmc** [comment]
![image](https://user-images.githubusercontent.com/13561350/64916508-2c3fc400-d776-11e9-8b84-62f83cfd1a52.png)
![image](https://user-images.githubusercontent.com/13561350/64916509-2f3ab480-d776-11e9-85b7-3040b52cce90.png)

**Comment by danielpmc** [comment]
Ok. fixed it you got to install ejs in the folder outside of the bot
